# Generated by Django 5.2 on 2025-04-26 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.category'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['posting_date'], name='blog_blogpo_posting_eda874_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['target_type', 'target_id'], name='blog_commen_target__97fd1f_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['posting_date'], name='blog_commen_posting_d8b85c_idx'),
        ),
    ]
